version: '3.9'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: >
      sh -c "cp .env.example .env &&
      yarn install && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - .:/app
